#!/usr/bin/env bash

# Source: http://rigor.com/blog/2015/12/optimizing-animated-gifs-with-html5-video

basename() {
    # Usage: basename "path" ["suffix"]
    local tmp

    tmp=${1%"${1##*[!/]}"}
    tmp=${tmp##*/}
    tmp=${tmp%"${2/"$tmp"}"}

    printf '%s\n' "${tmp:-/}"
}

dirname() {
    # Usage: dirname "path"
    local tmp=${1:-.}

    [[ $tmp != *[!/]* ]] && {
        printf '/\n'
        return
    }

    tmp=${tmp%%"${tmp##*[!/]}"}

    [[ $tmp != */* ]] && {
        printf '.\n'
        return
    }

    tmp=${tmp%/*}
    tmp=${tmp%%"${tmp##*[!/]}"}

    printf '%s\n' "${tmp:-/}"
}

if [[ -z $1 ]]; then
    printf "Usage: gif2mp4 animated.gif\n"
    exit 1
fi

if [[ ! -f $1 ]]; then
    echo "$1 not exists"
    exit 1
fi

abs_path=$(realpath $1)
basename=$(basename $abs_path .gif)

if [[ -z "$2" ]]; then
    target_path="${basename}.mp4"
else
    target_path=$2
fi

ffmpeg -i $abs_path -movflags faststart -pix_fmt yuv420p -vf "scale=trunc(iw/2)*2:trunc(ih/2)*2" $target_path

